version: "3.2"
services:
  jupyter3:
    hostname: jupyter3
    image: loicberthou/jupyter3:5.1.0
    command: ["/opt/conda/bin/jupyter", "notebook", "--notebook-dir=/opt/notebooks", "--ip='*'", "--port=8888", "-y", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - notebooks:/opt/notebooks
      - ./data:/tmp/data
    logging:
      options:
        max-size: "500m"
        max-file: "10"
volumes:
  notebooks:
